title: "Kintone Associate Mock Exam"
baseurl: "/kintone_quiz"
markdown: kramdown
repository: zin1985/kintone_quiz
plugins:
  - jekyll-seo-tag
  - jekyll-feed
concurrency:
  group: "pages-deploy"
  cancel-in-progress: true
